#+title: ~WireCell::Img::BlobDepoFill~

Replaces charge in blobs with that from overlapping depos.

* Overview

The ~BlobDepoFill~ WCT flow graph node is a join node which accepts an
~IBlobSet~ on input port 0 and an ~IDepoSet~ on input port 1 and produces
an ~IBlobSet~ on output port 0.

The output retains all information from the input ~IBlobSet~ except that
the charge of each blob is replaced with the charge of all input depos
in the blob volume.

In order to allow depos to align witgh blobs the depos provided should
as output by a ~Drifter~ flow graph node.  The input deposet may extend
transversely beyond the anode plane of any given blob as any depos not
in the sensitive area of the anode face associated with a blob will be
ignored.

* Algorithm

The goal is to integrate the depo charge distribution over the volume
of each blob.  This ends up being rather complex for a few reasons.

- depo-to-blob overlap represents an N-to-M mapping with no direct way
  to form.

- both depos and blobs are numerous and the mapping is sparse.

- depos have truncated 3D Gaussian extent both longitudinally and
  transverse this extent varies substantially across the depos.

- blobs have irregular and varied shape defined in terms boundaries
  which are defined by wire rays.
  
The algorithm joins the volumes of depos with the volumes of blobs in
a series of reduction of the possible space.

1. Narrow to a single ~IAnodeFace~
2. Narrow to a single ~ISlice~
3. Produce an "~s-d-w~ graph" (described below)
4. Narrow to a single ~IDepo~
5. Narrow to a single ~IWire~
6. Iterate over blobs

The ~s-d-w~ directed (acyclic) graph associates slices to depos (~s-d~
edges) and depos to wires (~d-w~ edges).  Both edge types represent the
orthogonal integration of the depo Gaussian over a section in one
dimension.

The ~s-d~ edge integrates the Gaussian along the longitudinal dimension
bounded by the slice's time span.  The edge holds the result of that
integral.

Likewise, the ~d-w~ edge represents the integral of a section of the
Gaussian in the direction transverse to the wires of the so called
"primary wire plane".  Which wire plane to use as "primary" is
configurable and the collection plane is the default.  The ~d-w~ edge
holds the result of this integral.

As the algorithm descends the narrowing from slice to depo to wire it
also descends the ~s-d-w~ graph.  Reaching the wires, the full ~s-d-w~
path is known and each blob in the current face and slice context is
checked to determine if it contains the current wire.  When it does
the final integral of the Gaussian is performed.  This requires
calculating the bounds on the current wire provided by blob boundary
rays from the other planes.  The three integrals from each dimension
then scale the depo charge and the result is added to a sum associated
with the current blob.
