#!/bin/bash

usage () {
    cat <<EOF

Run tests in one or more software installations.

A software installation environment MUST be configured with direnv.

Usage:

  multi-direnv-testing [options] [/path/to/release ...]
 
Options:

  -t|--tag give a BATS tag on which to filter [default=history]
  -n|--dry-run will only print the commands

Multiple -t|--tags may be given.

If no release directories are given, the current environment is used.

Example for bv@haiku:

  ./test/scripts/multi-release-testing ~/wrk/wct/rel2? (pwd)

EOF
    exit 1
}

SHELL=bash

declare -a releases
declare -a tags
faker=""
while [[ $# -gt 0 ]] ; do
    case $1 in
        -t|--tag) tags+=( "$2" ); shift 2;;
        -n|--dry-run) faker="echo"; shift;;
        -*) usage;;
        *) releases+=( "$1" ); shift;;
    esac
done

function die () {
    echo "$@" 1>&2
    exit 1
}

echo "RELEASES: ${releases[*]}"

scrdir="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
topdir="$(realpath "${scrdir}"/../..)"
cd "$topdir" || die "Can not cd to $topdir"


if [ "${#releases[@]}" -eq 0 ] ; then
    releases=( "$topdir" )
fi
if [ "${#tags[@]}" ] ; then
    tags=( "history" )
fi

declare -a tag_args
for tag in "${tags[@]}"
do
    tag_args+=( --filter-tags "$tag" )
done

# requires GNU sort
function verlte () {
    printf '%s\n' "$1" "$2" | sort -C -V
}


# Build a pair of linked lists of release directories and tests
declare -a rels
declare -a files
for rel in "${releases[@]}"
do
    ver=$( "$scrdir"/run-in-direnv "$rel" wire-cell --version )
    echo "CONSIDERING release $ver in $rel" 1>&2

    verlte "$ver" "0.20" && continue

    rels+=( "$rel" )
    files+=( "$topdir/gen/test/test-addnoise.bats" )
    echo "ADDING test-addnoise.bats" 1>&2

    rels+=( "$rel" )
    files+=( "$topdir/test/test/test-pdsp-simsn-nfsp.bats" )
    echo "ADDING test-pdsp-simsn.bats" 1>&2

    rels+=( "$rel" )
    files+=( "$topdir/gen/test/test-noise-roundtrip.bats" )
    echo "ADDING gen/test/test-noise-roundtrip.bats" 1>&2

    verlte "$ver" "0.24.1" && continue

    rels+=( "$rel" )
    files+=( "$topdir/img/test/test-wct-uboone-img.bats" )
    echo "ADDING test-wct-uboone-img.bats" 1>&2

done

echo "RELEASES: ${rels[*]}"


# Starting with 0.25:
# history_tests+=( img/test/test-wct-uboone-img.bats )

# echo -- \
parallel --link \
         "$faker" "$scrdir/run-in-direnv" '{1}' "$topdir/test/bats/bin/bats" "${tag_args[@]}" '{2}' \
         ::: "${rels[@]}" \
         ::: "${files[@]}"
